## Data Cleaning
    - Before data cleaning , we must have the idea that if the data is having any missing value or not or any duplicate value or not.
        - For missing value check use : isNull()
            - Syntax:
                df.isNull() => Shows boolean in dataframe.
                df.isNull().sum() => for total missing value count for each column.

        - For duplicate values check: duplicated()

In [ ]:
import pandas as pd

df = pd.read_csv("student_depression_dataset.csv")

In [ ]:
df.isnull()

In [ ]:
df.isnull().sum()

## Mathematical Functions in DataFrame

1. `sum()`    ⇒ Calculates the sum of all values present in a column or in multiple columns.
2. `mean()`   ⇒ Calculates the average of all values or mean of all values in a column.
3. `min()`    ⇒ Returns minimum value in a column.
4. `max()`    ⇒ Return maximum value in a column.
5. `median()` ⇒ Calculates the median value of a column.
6. `var()`    ⇒ Calculates the variance of all the values in a column.
7. `axis`     ⇒ It helps us calculate the mathematical calculation row-wise or column-wise.
              `row-wise      ⇒   axis = 1`
              `column-wise   ⇒   axis = 0`

In [8]:
df.sum()

np.int64(18)

- Accessing particular column.

In [ ]:
df['Age']

In [10]:
df['Age'].mean()

np.float64(25.82230027597577)

In [11]:
type(df['Age'])

pandas.core.series.Series

- Selecting multiple columns.

In [18]:
df[['Age', 'Sleep Duration', 'City']].head()

   Age       Sleep Duration           City
0   33          '5-6 hours'  Visakhapatnam
1   24          '5-6 hours'      Bangalore
2   31  'Less than 5 hours'       Srinagar
3   28          '7-8 hours'       Varanasi
4   25          '5-6 hours'         Jaipur

- Select specific rows of our data frame.
    - loc[]     ⇒  location
        - It fetches the record as per the labeled index location of the value.
    - iloc[]    ⇒  integer location
        - It fetches the record as per the integer index location

In [27]:
df.loc[499]

id                                                      2589
Gender                                                  Male
Age                                                       25
City                                                  Mumbai
Profession                                           Student
Academic Pressure                                          5
Work Pressure                                              0
CGPA                                                    6.51
Study Satisfaction                                         2
Job Satisfaction                                           0
Sleep Duration                           'Less than 5 hours'
Dietary Habits                                     Unhealthy
Degree                                                   MSc
Have you ever had suicidal thoughts ?                     No
Work/Study Hours                                          10
Financial Stress                                           3
Family History of Mental Illness                          No
Depression                                                 0
Name: 499, dtype: object

In [25]:
df.iloc[500]

id                                                      2591
Gender                                                  Male
Age                                                       21
City                                                  Mumbai
Profession                                           Student
Academic Pressure                                          1
Work Pressure                                              0
CGPA                                                    7.09
Study Satisfaction                                         5
Job Satisfaction                                           0
Sleep Duration                           'More than 8 hours'
Dietary Habits                                       Healthy
Degree                                                   MCA
Have you ever had suicidal thoughts ?                     No
Work/Study Hours                                           4
Financial Stress                                           5
Family History of Mental Illness                         Yes
Depression                                                 0
Name: 500, dtype: object

- Slicing records

In [29]:
df.iloc[0:6]

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33,Visakhapatnam,Student,5,0,8.97,2,0,'5-6 hours',Healthy,B.Pharm,Yes,3,1,No,1
1,8,Female,24,Bangalore,Student,2,0,5.90,5,0,'5-6 hours',Moderate,BSc,No,3,2,Yes,0
2,26,Male,31,Srinagar,Student,3,0,7.03,5,0,'Less than 5 hours',Healthy,BA,No,9,1,Yes,0
3,30,Female,28,Varanasi,Student,3,0,5.59,2,0,'7-8 hours',Moderate,BCA,Yes,4,5,Yes,1
4,32,Female,25,Jaipur,Student,4,0,8.13,3,0,'5-6 hours',Moderate,M.Tech,Yes,1,1,No,0
5,33,Male,29,Pune,Student,2,0,5.70,3,0,'Less than 5 hours',Healthy,PhD,No,4,1,No,0

In [34]:
df_labeled = df.set_index('City')

In [36]:
df_labeled.loc[['Bangalore']].head(3)

,id,Gender,Age,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
City,,,,,,,,,,,,,,,,,
Bangalore,8,Female,24,Student,2,0,5.90,5,0,'5-6 hours',Moderate,BSc,No,3,2,Yes,0
Bangalore,173,Male,18,Student,4,0,7.10,3,0,'More than 8 hours',Unhealthy,'Class 12',Yes,11,5,Yes,1
Bangalore,623,Female,23,Student,5,0,5.66,1,0,'Less than 5 hours',Unhealthy,MCA,Yes,11,4,No,1

- Fetching Specific number of rows and Specific columns

In [39]:
df.loc[0:5,['City', 'Age','Gender', 'Sleep Duration']]

            City  Age  Gender       Sleep Duration
0  Visakhapatnam   33    Male          '5-6 hours'
1      Bangalore   24  Female          '5-6 hours'
2       Srinagar   31    Male  'Less than 5 hours'
3       Varanasi   28  Female          '7-8 hours'
4         Jaipur   25  Female          '5-6 hours'
5           Pune   29    Male  'Less than 5 hours'

In [44]:
df_labeled.iloc[23:28,1:6]

           Gender  Age Profession  Academic Pressure  Work Pressure
City
Thane        Male   23    Student                  1              0
Bangalore    Male   18    Student                  4              0
Mumbai     Female   20    Student                  5              0
Ahmedabad    Male   31    Student                  2              0
Lucknow      Male   25    Student                  3              0